@startuml
skinparam database<<submodule>> {
  backgroundColor aliceblue
  borderColor blue
}
skinparam frame<<main>> {
  backgroundColor aliceblue
  borderColor blue
  borderThickness 2
}
'skinparam linetype polyline

database "Integration Repository" as Integration {
    frame "main branch" as integration_main   #line.bold;line:red {
        database  "ComponentA" as Integration_main_ComponentA<<submodule>>  #line.dotted
        database  "ComponentB" as Integration_main_ComponentB<<submodule>>  #line.dotted
        database  "ComponentC" as Integration_main_ComponentC<<submodule>>  #line.dotted
        database  "ComponentD" as Integration_main_ComponentD<<submodule>>  #line.dotted
        
        'Integration_main_ComponentA -[hidden]-> Integration_main_ComponentB
        Integration_main_ComponentA -[hidden]- Integration_main_ComponentC
        Integration_main_ComponentA -[hidden]- Integration_main_ComponentD
    }
    
    Integration_main_ComponentA --> ComponentA_main
    Integration_main_ComponentB --> ComponentB_main
    Integration_main_ComponentC --> ComponentC_main
    Integration_main_ComponentD --> ComponentD_main
     

    
    frame "feature2 branch" as integration_feature2  #line:blue  {
        database  "ComponentA" as Integration_feature2_ComponentA<<submodule>>  #line.dotted
        database  "ComponentB" as Integration_feature2_ComponentB<<submodule>>  #line.dotted
        database  "ComponentC" as Integration_feature2_ComponentC<<submodule>>  #line.dotted
        database  "ComponentD" as Integration_feature2_ComponentD<<submodule>>  #line.dotted
        
        
        'Integration_feature2_ComponentA -[hidden]- Integration_feature2_ComponentB
        Integration_feature2_ComponentA -[hidden]- Integration_feature2_ComponentC
        Integration_feature2_ComponentA -[hidden]- Integration_feature2_ComponentD
    }
    
    Integration_feature2_ComponentA -[#blue]> ComponentA_main
    Integration_feature2_ComponentB -[#blue]> ComponentB_feature2
    Integration_feature2_ComponentC -[#blue]> ComponentC_main
    Integration_feature2_ComponentD -[#blue]> ComponentD_main
    
    frame "feature3 branch" as integration_feature3  #line:orange  {
        database  "ComponentA" as Integration_feature3_ComponentA<<submodule>>  #line.dotted
        database  "ComponentB" as Integration_feature3_ComponentB<<submodule>>  #line.dotted
        database  "ComponentC" as Integration_feature3_ComponentC<<submodule>>  #line.dotted
        database  "ComponentD" as Integration_feature3_ComponentD<<submodule>>  #line.dotted
        
        
        'Integration_feature3_ComponentA -[hidden]-> Integration_feature3_ComponentB
        Integration_feature3_ComponentA -[hidden]-> Integration_feature3_ComponentC
        Integration_feature3_ComponentA -[hidden]-> Integration_feature3_ComponentD
    }
    
    Integration_feature3_ComponentA -[#orange]> ComponentA_feature3
    Integration_feature3_ComponentB -[#orange]> ComponentB_feature3
    Integration_feature3_ComponentC -[#orange]> ComponentC_main
    Integration_feature3_ComponentD -[#orange]> ComponentD_main
    
    integration_main -[hidden]--- integration_feature2
    integration_feature2 -[hidden]--- integration_feature3
}

    
rectangle "Component repositories" as components #line.dashed {
	database ComponentA {
	    frame "main branch" as ComponentA_main  #line.bold;line:blue {
	    }
	    frame "feature1 branch" as ComponentA_feature1 #line.dashed {
	    }
	    frame "feature3 branch" as ComponentA_feature3 {
	    }
	    ComponentA_main -[hidden]-> ComponentA_feature1
	    ComponentA_feature1 -[hidden]-> ComponentA_feature3
	}
	database ComponentB {
	    frame "main branch" as ComponentB_main   #line.bold;line:blue {
	    }
	    frame "feature1 branch" as ComponentB_feature1 #line.dashed {
	    }
	    frame "feature2 branch" as ComponentB_feature2 {
	    }
	    frame "feature3 branch" as ComponentB_feature3 {
	    }
	    ComponentB_main -[hidden]- ComponentB_feature1
	    ComponentB_feature1 -[hidden]- ComponentB_feature2
	    ComponentB_feature2 -[hidden]- ComponentB_feature3
	}
	
	database ComponentC {
	    frame "main branch" as ComponentC_main   #line.bold;line:blue {
	    }
	    frame "feature1 branch" as ComponentC_feature1 #line.dashed {
	    }
	    ComponentC_main -[hidden]-> ComponentC_feature1
	}
	database ComponentD {
	    frame "main branch" as ComponentD_main   #line.bold;line:blue {
	    }
	}
    note as note_feature1
    	feature 1 branch is inactive 
    	for	more than 90 days 
    	in all component repositories
    end note	
	
	
	ComponentA -[hidden]- ComponentB
	ComponentB -[hidden]- ComponentC
	ComponentC -[hidden]-- ComponentD
	ComponentA -[hidden]--- note_feature1
}

@enduml
